services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.5.1
    container_name: mlflow-server
    ports:
      - "8000:8000"
    volumes:
      - mlflow_mlrun:/mlruns
      - mlflow_mlartifacts:/mlartifacts
    environment:
      MLFLOW_SERVER_ALLOWED_HOSTS: "*"
    command: >
      mlflow server
      --host 0.0.0.0 
      --port 8000
      --static-prefix /mlflow
    networks:
      - mlops-nw

  labelstudio:
    image: heartexlabs/label-studio:1.21.0
    container_name: labelstudio-server # Correct key
    ports:
      - "8080:8080"
    volumes:
      - label_studio_data:/label-studio/data
    networks:
      - mlops-nw
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST}
      - LABEL_STUDIO_DB=${LABEL_STUDIO_DB}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
  
  backend:
    container_name: backend-mlserver
    image: ghcr.io/231031/mobile-sentiment-ops/mlops_mbs_backend:${DOCKER_TAG}
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      REPORTS_DIR: ${REPORTS_DIR}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      INITIAL_DATA_PATH: ${INITIAL_DATA_PATH}
      PYTHONPATH: /backend
    volumes:
      - ./app/credential.json:/backend/credential.json
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - mlops-nw

  # from frontend prod image

volumes:
  label_studio_data:
  mlflow_mlrun:
  mlflow_mlartifacts:

networks:
  mlops-nw:
    driver: bridge
