services:
  # --- 1. Shared Database (Single Container) ---
  db:
    container_name: mlops-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - labelstudio_db_data:/var/lib/postgresql/data
      - ./db_init/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - mlops-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- 2. GCS Emulator ---
  gcs-emulator:
    image: fsouza/fake-gcs-server
    command: [ "-scheme", "http", "-port", "4443", "-external-url", "http://gcs-emulator:4443" ]
    ports:
      - "4443:4443"
    volumes:
      - storage_data:/storage
    networks:
      - mlops-net

  # --- 3. MLflow Server ---
  mlflow:
    container_name: mlflow-server
    image: ghcr.io/mlflow/mlflow:v3.5.1
    ports:
      - "8000:8000"
    environment:
      MLFLOW_SERVER_ALLOWED_HOSTS: "*"
    command: >
      mlflow server  --host 0.0.0.0 --port 8000
    volumes:
      - mlflow_mlrun:/mlruns
      - mlflow_mlartifacts:/mlartifacts
    networks:
      - mlops-net

  # --- 4. Label Studio ---
  label-studio:
    container_name: labelstudio-server
    image: heartexlabs/label-studio:1.21.0
    ports:
      - "8081:8080"
    environment:
      DJANGO_DB: default
      POSTGRE_NAME: ${POSTGRE_NAME}
      POSTGRE_USER: ${POSTGRES_USER}
      POSTGRE_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRE_HOST: ${POSTGRE_HOST}
      POSTGRE_PORT: 5432
      LABEL_STUDIO_USERNAME: ${LABEL_STUDIO_USERNAME}
      LABEL_STUDIO_PASSWORD: ${LABEL_STUDIO_PASSWORD}
      LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK: ${LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK}
    volumes:
      - label_studio_data:/label-studio/data
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mlops-net

  # --- 5. Your API ---
  backend:
    container_name: backend-model-server
    image: mlops_backend:latest
    build:
      context: .
      dockerfile: app/Dockerfile.backend
    command: uvicorn app.ml_server:app --host 0.0.0.0 --port 5001 --reload
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      GCS_ENDPOINT: ${GCS_STORAGE_EMULATOR_HOST}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      REPORTS_DIR: ${REPORTS_DIR}
      INITIAL_DATA_PATH: ${INITIAL_DATA_PATH}
      PYTHONPATH: /backend
    volumes:
      - ./data:/backend/data
      - ./report:/backend/report
      - ./lib:/backend/lib
      - ./app:/backend/app
    depends_on:
      - mlflow
      - gcs-emulator
    networks:
      - mlops-net

  # --- 6. Frontend ---
  frontend:
    container_name: mlops-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - mlops-net

volumes:
  label_studio_data:
  labelstudio_db_data:
  mlflow_mlrun:
  mlflow_mlartifacts:
  storage_data:


networks:
  mlops-net:
    driver: bridge
